export const quoteData = [
  { id: "q-001", text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus", category: "Growth", tags: ["progress", "discipline"] },
  { id: "q-002", text: "As long as you live, keep learning how to live.", author: "Seneca", category: "Growth", tags: ["learning", "life"] },
  { id: "q-003", text: "I am a slow walker, but I never walk back.", author: "Abraham Lincoln", category: "Growth", tags: ["progress", "persistence"] },
  { id: "q-004", text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche", category: "Growth", tags: ["purpose", "endurance"] },
  { id: "q-005", text: "Small steps still belong to the road.", author: "QuoteDrop", category: "Growth", tags: ["progress", "patience"] },
  { id: "q-006", text: "Growth often arrives dressed as repetition.", author: "QuoteDrop", category: "Growth", tags: ["practice", "discipline"] },
  { id: "q-007", text: "Become familiar with beginnings; they are where change learns your name.", author: "QuoteDrop", category: "Growth", tags: ["beginnings", "change"] },
  { id: "q-008", text: "You do not need a new life to take one better step.", author: "QuoteDrop", category: "Growth", tags: ["progress", "life"] },
  { id: "q-009", text: "Keep becoming someone your future can recognize.", author: "QuoteDrop", category: "Growth", tags: ["future", "identity"] },

  { id: "q-010", text: "The unexamined life is not worth living.", author: "Socrates", category: "Life", tags: ["reflection", "meaning"] },
  { id: "q-011", text: "All the world's a stage, and all the men and women merely players.", author: "William Shakespeare", category: "Life", tags: ["humanity", "perspective"] },
  { id: "q-012", text: "There is no charm equal to tenderness of heart.", author: "Jane Austen", category: "Life", tags: ["kindness", "character"] },
  { id: "q-013", text: "The mass of men lead lives of quiet desperation.", author: "Henry David Thoreau", category: "Life", tags: ["truth", "reflection"] },
  { id: "q-014", text: "A full life is not always a loud one.", author: "QuoteDrop", category: "Life", tags: ["quiet", "meaning"] },
  { id: "q-015", text: "Some days are chapters; some are only commas.", author: "QuoteDrop", category: "Life", tags: ["time", "perspective"] },
  { id: "q-016", text: "Pay attention to the ordinary; most of life lives there.", author: "QuoteDrop", category: "Life", tags: ["presence", "ordinary"] },
  { id: "q-017", text: "A meaningful day does not have to be a remarkable day.", author: "QuoteDrop", category: "Life", tags: ["meaning", "contentment"] },
  { id: "q-018", text: "Leave a little room in your plans for being human.", author: "QuoteDrop", category: "Life", tags: ["grace", "balance"] },

  { id: "q-019", text: "The imagination is not a state: it is the human existence itself.", author: "William Blake", category: "Creativity", tags: ["imagination", "art"] },
  { id: "q-020", text: "A thing of beauty is a joy for ever.", author: "John Keats", category: "Creativity", tags: ["beauty", "art"] },
  { id: "q-021", text: "Poets are the unacknowledged legislators of the world.", author: "Percy Bysshe Shelley", category: "Creativity", tags: ["poetry", "ideas"] },
  { id: "q-022", text: "Every artist was first an amateur.", author: "Ralph Waldo Emerson", category: "Creativity", tags: ["practice", "art"] },
  { id: "q-023", text: "Make the thing before you explain the thing.", author: "QuoteDrop", category: "Creativity", tags: ["making", "practice"] },
  { id: "q-024", text: "An idea becomes braver when you give it a page.", author: "QuoteDrop", category: "Creativity", tags: ["ideas", "writing"] },
  { id: "q-025", text: "Your first draft is allowed to arrive without manners.", author: "QuoteDrop", category: "Creativity", tags: ["writing", "beginnings"] },
  { id: "q-026", text: "Curiosity is often creativity before it finds a form.", author: "QuoteDrop", category: "Creativity", tags: ["curiosity", "ideas"] },
  { id: "q-027", text: "Create something small enough to finish and honest enough to matter.", author: "QuoteDrop", category: "Creativity", tags: ["making", "focus"] },

  { id: "q-028", text: "Cowards die many times before their deaths; the valiant never taste of death but once.", author: "William Shakespeare", category: "Courage", tags: ["bravery", "fear"] },
  { id: "q-029", text: "If there is no struggle, there is no progress.", author: "Frederick Douglass", category: "Courage", tags: ["struggle", "progress"] },
  { id: "q-030", text: "Courage is resistance to fear, mastery of fear, not absence of fear.", author: "Mark Twain", category: "Courage", tags: ["fear", "strength"] },
  { id: "q-031", text: "Life is either a daring adventure or nothing.", author: "Helen Keller", category: "Courage", tags: ["adventure", "boldness"] },
  { id: "q-032", text: "Courage can be quiet enough to sound like one more try.", author: "QuoteDrop", category: "Courage", tags: ["persistence", "fear"] },
  { id: "q-033", text: "Do the honest thing before you feel ready to be brave.", author: "QuoteDrop", category: "Courage", tags: ["honesty", "action"] },
  { id: "q-034", text: "Fear may ride with you; it does not have to steer.", author: "QuoteDrop", category: "Courage", tags: ["fear", "choice"] },
  { id: "q-035", text: "A small act of nerve can redraw a whole afternoon.", author: "QuoteDrop", category: "Courage", tags: ["action", "boldness"] },
  { id: "q-036", text: "You can be uncertain and still move forward.", author: "QuoteDrop", category: "Courage", tags: ["uncertainty", "progress"] },

  { id: "q-037", text: "Knowledge itself is power.", author: "Francis Bacon", category: "Wisdom", tags: ["knowledge", "learning"] },
  { id: "q-038", text: "A little learning is a dangerous thing.", author: "Alexander Pope", category: "Wisdom", tags: ["learning", "humility"] },
  { id: "q-039", text: "The fool doth think he is wise, but the wise man knows himself to be a fool.", author: "William Shakespeare", category: "Wisdom", tags: ["humility", "self-knowledge"] },
  { id: "q-040", text: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius", category: "Wisdom", tags: ["knowledge", "humility"] },
  { id: "q-041", text: "Wisdom often begins when certainty loosens its grip.", author: "QuoteDrop", category: "Wisdom", tags: ["humility", "reflection"] },
  { id: "q-042", text: "Listen long enough for your first answer to become a better question.", author: "QuoteDrop", category: "Wisdom", tags: ["listening", "questions"] },
  { id: "q-043", text: "Not every thought deserves a throne.", author: "QuoteDrop", category: "Wisdom", tags: ["thinking", "discernment"] },
  { id: "q-044", text: "A useful truth can survive being examined.", author: "QuoteDrop", category: "Wisdom", tags: ["truth", "reflection"] },
  { id: "q-045", text: "Learn the difference between a signal and a mood.", author: "QuoteDrop", category: "Wisdom", tags: ["discernment", "clarity"] },

  { id: "q-046", text: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson", category: "Friendship", tags: ["friendship", "giving"] },
  { id: "q-047", text: "Friendship is certainly the finest balm for the pangs of disappointed love.", author: "Jane Austen", category: "Friendship", tags: ["friendship", "comfort"] },
  { id: "q-048", text: "What do we live for, if it is not to make life less difficult to each other?", author: "George Eliot", category: "Friendship", tags: ["kindness", "community"] },
  { id: "q-049", text: "A friend to all is a friend to none.", author: "Aristotle", category: "Friendship", tags: ["friendship", "loyalty"] },
  { id: "q-050", text: "Good friendship makes room without keeping score.", author: "QuoteDrop", category: "Friendship", tags: ["friendship", "generosity"] },
  { id: "q-051", text: "Some people make the room feel more like home.", author: "QuoteDrop", category: "Friendship", tags: ["belonging", "friendship"] },
  { id: "q-052", text: "A true friend can hear the sentence you did not finish.", author: "QuoteDrop", category: "Friendship", tags: ["listening", "connection"] },
  { id: "q-053", text: "Friendship grows in the ordinary minutes we remember to share.", author: "QuoteDrop", category: "Friendship", tags: ["time", "connection"] },
  { id: "q-054", text: "Keep people who let you be unfinished.", author: "QuoteDrop", category: "Friendship", tags: ["acceptance", "friendship"] },

  { id: "q-055", text: "Love looks not with the eyes, but with the mind.", author: "William Shakespeare", category: "Love", tags: ["love", "perception"] },
  { id: "q-056", text: "How do I love thee? Let me count the ways.", author: "Elizabeth Barrett Browning", category: "Love", tags: ["love", "poetry"] },
  { id: "q-057", text: "There is only one happiness in this life, to love and be loved.", author: "George Sand", category: "Love", tags: ["love", "happiness"] },
  { id: "q-058", text: "The love that moves the sun and the other stars.", author: "Dante Alighieri", category: "Love", tags: ["love", "wonder"] },
  { id: "q-059", text: "Love is attention practiced over time.", author: "QuoteDrop", category: "Love", tags: ["attention", "care"] },
  { id: "q-060", text: "Make affection visible in the small logistics of a day.", author: "QuoteDrop", category: "Love", tags: ["care", "daily-life"] },
  { id: "q-061", text: "Being known gently is one of love's quietest gifts.", author: "QuoteDrop", category: "Love", tags: ["gentleness", "connection"] },
  { id: "q-062", text: "Love is not less real because it is ordinary.", author: "QuoteDrop", category: "Love", tags: ["ordinary", "love"] },
  { id: "q-063", text: "Say the kind thing while there is still time to say it.", author: "QuoteDrop", category: "Love", tags: ["kindness", "presence"] },

  { id: "q-064", text: "The art of being wise is the art of knowing what to overlook.", author: "William James", category: "Focus", tags: ["focus", "wisdom"] },
  { id: "q-065", text: "Nothing can bring you peace but yourself.", author: "Ralph Waldo Emerson", category: "Focus", tags: ["peace", "attention"] },
  { id: "q-066", text: "No great thing is created suddenly.", author: "Epictetus", category: "Focus", tags: ["patience", "work"] },
  { id: "q-067", text: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "Focus", tags: ["starting", "action"] },
  { id: "q-068", text: "Attention is a budget; spend it where tomorrow can feel it.", author: "QuoteDrop", category: "Focus", tags: ["attention", "priority"] },
  { id: "q-069", text: "One clear hour can rescue a scattered day.", author: "QuoteDrop", category: "Focus", tags: ["time", "clarity"] },
  { id: "q-070", text: "Protect the work that needs your undivided mind.", author: "QuoteDrop", category: "Focus", tags: ["work", "attention"] },
  { id: "q-071", text: "Finish the sentence before opening another tab.", author: "QuoteDrop", category: "Focus", tags: ["focus", "digital-life"] },
  { id: "q-072", text: "The next right thing is enough to begin with.", author: "QuoteDrop", category: "Focus", tags: ["priority", "action"] },

  { id: "q-073", text: "Well done is better than well said.", author: "Benjamin Franklin", category: "Success", tags: ["action", "work"] },
  { id: "q-074", text: "Always bear in mind that your own resolution to succeed is more important than any other.", author: "Abraham Lincoln", category: "Success", tags: ["resolve", "success"] },
  { id: "q-075", text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison", category: "Success", tags: ["work", "effort"] },
  { id: "q-076", text: "Success is a science; if you have the conditions, you get the result.", author: "Oscar Wilde", category: "Success", tags: ["success", "conditions"] },
  { id: "q-077", text: "Success becomes sturdier when it can survive a boring Tuesday.", author: "QuoteDrop", category: "Success", tags: ["consistency", "work"] },
  { id: "q-078", text: "Build systems your motivation does not have to carry.", author: "QuoteDrop", category: "Success", tags: ["systems", "discipline"] },
  { id: "q-079", text: "Progress that repeats is more useful than effort that performs.", author: "QuoteDrop", category: "Success", tags: ["consistency", "progress"] },
  { id: "q-080", text: "Let the result be the applause.", author: "QuoteDrop", category: "Success", tags: ["results", "work"] },
  { id: "q-081", text: "A good process is success before the headline arrives.", author: "QuoteDrop", category: "Success", tags: ["process", "success"] },

  { id: "q-082", text: "Fire is the test of gold; adversity, of strong men.", author: "Seneca", category: "Resilience", tags: ["adversity", "strength"] },
  { id: "q-083", text: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus", category: "Resilience", tags: ["response", "strength"] },
  { id: "q-084", text: "You have power over your mind—not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius", category: "Resilience", tags: ["mind", "strength"] },
  { id: "q-085", text: "Fall seven times, stand up eight.", author: "Japanese Proverb", category: "Resilience", tags: ["persistence", "recovery"] },
  { id: "q-086", text: "Rest can be part of resilience, not evidence against it.", author: "QuoteDrop", category: "Resilience", tags: ["rest", "recovery"] },
  { id: "q-087", text: "Some strength looks like starting smaller the second time.", author: "QuoteDrop", category: "Resilience", tags: ["recovery", "beginnings"] },
  { id: "q-088", text: "Bend the plan before you break yourself.", author: "QuoteDrop", category: "Resilience", tags: ["adaptation", "care"] },
  { id: "q-089", text: "You can carry the lesson without carrying the whole wound.", author: "QuoteDrop", category: "Resilience", tags: ["healing", "learning"] },
  { id: "q-090", text: "Begin again with the information the first attempt gave you.", author: "QuoteDrop", category: "Resilience", tags: ["learning", "restart"] },

  { id: "q-091", text: "Happiness depends upon ourselves.", author: "Aristotle", category: "Happiness", tags: ["happiness", "choice"] },
  { id: "q-092", text: "Think only of the past as its remembrance gives you pleasure.", author: "Jane Austen", category: "Happiness", tags: ["memory", "joy"] },
  { id: "q-093", text: "Joy is not in things; it is in us.", author: "Richard Wagner", category: "Happiness", tags: ["joy", "inner-life"] },
  { id: "q-094", text: "The most wasted of all days is one without laughter.", author: "E. E. Cummings", category: "Happiness", tags: ["laughter", "joy"] },
  { id: "q-095", text: "Happiness often enters through a door marked enough.", author: "QuoteDrop", category: "Happiness", tags: ["contentment", "enough"] },
  { id: "q-096", text: "A good moment does not need permission to count.", author: "QuoteDrop", category: "Happiness", tags: ["joy", "presence"] },
  { id: "q-097", text: "Notice what made today softer.", author: "QuoteDrop", category: "Happiness", tags: ["gratitude", "presence"] },
  { id: "q-098", text: "Tiny delights are still evidence.", author: "QuoteDrop", category: "Happiness", tags: ["joy", "small-things"] },
  { id: "q-099", text: "Leave some space in the day for something you did not optimize.", author: "QuoteDrop", category: "Happiness", tags: ["rest", "joy"] },

  { id: "q-100", text: "The old order changeth, yielding place to new.", author: "Alfred Tennyson", category: "Change", tags: ["change", "time"] },
  { id: "q-101", text: "We know what we are, but know not what we may be.", author: "William Shakespeare", category: "Change", tags: ["possibility", "identity"] },
  { id: "q-102", text: "Nothing endures but change.", author: "Heraclitus", category: "Change", tags: ["change", "time"] },
  { id: "q-103", text: "When we are no longer able to change a situation, we are challenged to change ourselves.", author: "Viktor Frankl", category: "Change", tags: ["change", "response"] },
  { id: "q-104", text: "Change is easier to meet when you stop demanding it arrive politely.", author: "QuoteDrop", category: "Change", tags: ["change", "acceptance"] },
  { id: "q-105", text: "A different season deserves a different routine.", author: "QuoteDrop", category: "Change", tags: ["seasons", "adaptation"] },
  { id: "q-106", text: "You are allowed to update the map after learning the terrain.", author: "QuoteDrop", category: "Change", tags: ["learning", "adaptation"] },
  { id: "q-107", text: "Not every ending is a verdict; some are directions.", author: "QuoteDrop", category: "Change", tags: ["endings", "beginnings"] },
  { id: "q-108", text: "Let the new version of the plan know what the old one taught you.", author: "QuoteDrop", category: "Change", tags: ["planning", "learning"] },
] as const;
  122